apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysqlchart.fullname" . }}
  labels:
    {{- include "mysqlchart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mysqlchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mysqlchart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mysqlchart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}        
          ports:
          - name: mysql
            containerPort: 3306
          env:
          {{- if .Values.mysqlAllowEmptyPassword }}
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "true"
          {{- end }}
          {{- if not (and .Values.allowEmptyRootPassword (not .Values.mysqlRootPassword)) }}
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "mysqlchart.secretName" . }}
                key: mysql-root-password
                {{- if .Values.mysqlAllowEmptyPassword }}
                optional: true
                {{- end }}
          {{- end }}
          {{- if not (and .Values.allowEmptyRootPassword (not .Values.mysqlPassword)) }}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "mysqlchart.secretName" . }}
                key: mysql-password
                {{- if or .Values.mysqlAllowEmptyPassword (empty .Values.mysqlUser) }}
                optional: true
                {{- end }}
          {{- end }}
          - name: MYSQL_USER
            value: {{ default "" .Values.mysqlUser | quote }}
          - name: MYSQL_DATABASE
            value: {{ default "" .Values.mysqlDatabase | quote }}
          {{- if .Values.timezone }}
          - name: TZ
            value: {{ .Values.timezone }}
          {{- end }}
          {{- if .Values.extraEnvVars }}
  {{ tpl .Values.extraEnvVars . | indent 8 }}
          {{- end }}          
          volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
            {{- if .Values.persistence.subPath }}
            subPath: {{ .Values.persistence.subPath }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:   
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "mysqlchart.fullname" .) }}            

